services:
  mongo_db:
    container_name: db_container
    image: mongo:7.0.2
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
  
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo_db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo_db:
