name: findmyplant-api CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          appdir: "backend"
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
