name: findmyplant-api CD

on:
  pull_request:
    branch:
      - main

jobs:
  build:
    name: Prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          appdir: "backend"
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

        env:
          NODE_ENV: production
          MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}  
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}  
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          CLOUD_KEY: ${{ secrets.CLOUD_KEY }}
          CLOUD_SECRET_KEY: ${{ secrets.CLOUD_SECRET_KEY }}